apiVersion: apps/v1
kind: Deployment
metadata:
 name: metabase-client
 labels:
   app: metabase-client
spec:
 selector:
  matchLabels:
   app: metabase-client
 template:
  metadata:
   labels:
    app: metabase-client
  spec:
   containers:
   - image: 192.168.0.118:5000/metabase/client:latest
     name: metabase-client
     imagePullPolicy: Always
     env:
     - name: HOST
       valueFrom:
         secretKeyRef:
          name: metabase-secrets
          key: HOST
     - name: NEXTAUTH_URL
       valueFrom:
         secretKeyRef:
          name: metabase-secrets
          key: NEXTAUTH_URL
     - name: NEXT_PUBLIC_SECRET
       valueFrom:
         secretKeyRef:
          name: metabase-secrets
          key: NEXT_PUBLIC_SECRET
     - name: JWT_KEY_PRIVATE
       valueFrom:
         secretKeyRef:
          name: metabase-secrets
          key: JWT_KEY_PRIVATE
     - name: JWT_KEY_PUBLIC
       valueFrom:
         secretKeyRef:
          name: metabase-secrets
          key: JWT_KEY_PUBLIC
     - name: NEXT_PUBLIC_TRPC_SERVER_URL
       valueFrom:
         secretKeyRef:
          name: metabase-secrets
          key: NEXT_PUBLIC_TRPC_SERVER_URL
     ports:
       - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: metabase-client-svc
spec:
  selector:
    app: metabase-client
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 80